import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import NavBar from "@/components/shared/NavBar";
import QuickAccessBar from "@/components/shared/QuickAccessBar";
import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-nunito",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Industria RLC - Academia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <NavBar />
        <QuickAccessBar />
        {children}
      </body>
    </html>
  );
}
