import type { Service } from "./types";

export const servicesData: Service[] = [
  {
    id: "electricidad",
    title: "Electricidad Industrial",
    slug: "electricidad",
    description: "Soluciones eléctricas para la industria.",
    subServices: [
      {
        id: "subestacion-electrica",
        title: "Subestación Eléctica",
        slug: "subestacion-electrica",
        description: "Diseño, construcción y mantenimiento de subestaciones eléctricas.",
        image: "https://images.unsplash.com/photo-1509390144018-eeaf65052242?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        detailedDescription: "Una subestación eléctrica es una instalación clave destinada a establecer los niveles de tensión adecuados para distribuir energía eléctrica. Compuesta por equipos como transformadores, interruptores y sistemas de protección, asegura un suministro estable y seguro de electricidad. \n\nIndustria RLC se encuentra comprometida con ofrecer soluciones de alta calidad. Contamos con diversos servicios a Subestaciones Eléctricas para una eficiente distribución de energía y protección de tu sistema eléctrico.",
        benefits: [
          "Diseño de subestaciones eléctricas",
          "Suministro a necesidad y pedido del cliente",
          "Instalación de subestaciones eléctricas",
          "Comisionamiento con pruebas dinámicas",
          "Capacitación para el personal",
          "Optimización de los equipos e instalaciones",
          "Mantenimiento preventivo, correctivo y predictivo",
        ],
        applications: [
          "Públicos",
          "Industriales",
          "Comerciales",
          "Residenciales",
          "Edificaciones",
          "Centros de Salud",
          "Centros de Estudios",
          "Minería"
        ]
      },
      {
        id: "tableros-electricos",
        title: "Tableros Eléctricos",
        slug: "tableros-electricos",
        description: "Fabricación e instalación de tableros eléctricos industriales.",
        image: "https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        detailedDescription: "Los tableros eléctricos son dispositivos que controlan y distribuyen la energía en un sistema eléctrico. Actúan como el centro de comando de la instalación, protegiendo y gestionando el flujo de corriente hacia diferentes circuitos y equipos. \n\n Industria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios a tableros eléctricos para una correcta distribución de energía y protección contra sobrecargas y cortocircuitos.",
        benefits: [
          "Diseño de tableros eléctricos",
          "Instalación de tableros eléctricos",
          "Mantenimiento de tableros eléctricos",
          "Megado de tableros eléctricos",
          "Certificado de operatividad de tableros eléctricos",
          "Optimización de los equipos e instalaciones",
          "Mantenimiento preventivo, correctivo y predictivo",
        ],
        applications: [
          "Públicos",
          "Industriales",
          "Comerciales",
          "Residenciales",
          "Edificaciones",
          "Centros de Salud",
          "Centros de Estudios",
          "Minería"
        ]
      },
      {
        id: "banco-condensadores",
        title: "Banco de Condensadores",
        slug: "banco-condensadores",
        description: "Instalación y mantenimiento de bancos de condensadores.",
        image: "https://i.ibb.co/WRVq0DG/bancodecondensadores.jpg",
        detailedDescription: "Un banco de condensadores es un conjunto de capacitores conectados en paralelo para mejorar el factor de potencia de una instalación eléctrica. Su función es aumentar el factor de potencia de un sistema eléctrico y compensar la energía reactiva de un sistema. \n\n Industria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios a bancos de condensadores para una correcta compensación de energía reactiva y mejorar la eficiencia energética de tu instalación eléctrica.",
        benefits: [
          "Suministro de banco de condensadores",
          "Instalación de banco de condensadores",
          "Mantenimiento de banco de condensadores",
          "Estudio de calidad de energía reactiva",
          "Optimización de los equipos e instalaciones",
          "Mantenimiento preventivo, correctivo y predictivo",
        ],
        applications: [
          "Edificios comerciales",
          "Plantas industriales",
          "Centros educativos",
          "Hospitales",
          "Hoteles",
          "Centros de datos"
        ]
      },
      {
        id: "arrancadores-suaves-y-variadores-de-frecuencia",
        title: "Arrancadores Suaves y Variadores de Frecuencia",
        slug: "arrancadores-suaves-y-variadores-de-frecuencia",
        description: "Suministro, instalación y mantenimiento de arrancadores suaves y variadores de frecuencia.",
        image: "https://i.ibb.co/C5W8BZHW/arracandoresvariadores.jpg",
        detailedDescription: "Un arrancador suave es un dispositivo que permite controlar la velocidad y el par de un motor eléctrico de forma suave y eficiente. Su función es reducir las sobrecargas y los picos de corriente al inicio del motor, prolongando la vida útil de los equipos y mejorando la eficiencia energética. \n\n Un variador de frecuencia es un dispositivo que permite ajustar la velocidad de un motor eléctrico de forma continua y precisa. Su función es ajustar la velocidad de un motor eléctrico de forma continua y precisa. \n\n Industria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de Arrancadores Suaves y Variadores de Frecuencia.",
        benefits: [
          "Suministro de arrancadores suaves y variadores de frecuencia",
          "Instalación de arrancadores suaves y variadores de frecuencia",
          "Mantenimiento de arrancadores suaves y variadores de frecuencia",
          "Configuración de variadores de frecuencia",
          "Certificado de operatividad de arrancadores suaves y variadores de frecuencia",
          "Optimización de los equipos e instalaciones",
          "Mantenimiento preventivo, correctivo y predictivo",
        ],
        applications: [
          "Edificios comerciales",
          "Plantas industriales",
          "Centros educativos",
          "Hospitales",
          "Hoteles",
          "Centros de datos"
        ]
      },
      {
        id: "sistema-de-puesta-a-tierra-y-pararrayos",
        title: "Sistema de puesta a tierra y pararrayos",
        slug: "sistema-de-puesta-a-tierra-y-pararrayos",
        description: "Suministro, instalación y mantenimiento de sistema de puesta a tierra y pararrayos.",
        image: "https://i.ibb.co/6JfbMJkY/puestatierrapararrayos.jpg",
        detailedDescription: "Un sistema de puesta a tierra es un conjunto de elementos que conectan la instalación eléctrica a tierra para proteger los equipos y personas contra descargas eléctricas. Un pararrayos es un dispositivo que protege la instalación eléctrica contra descargas eléctricas. \n\n Industria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de Sistema de Puesta a Tierra y Pararrayos desde instalaciones hasta el mantenimiento.",
        benefits: [
          "Suministro de sistema de puesta a tierra y pararrayos",
          "Instalación de sistema de puesta a tierra y pararrayos",
          "Mantenimiento de sistema de puesta a tierra y pararrayos",
          "Prueba de puesta a tierra y pararrayos",
          "Optimización de los equipos e instalaciones",
          "Mantenimiento preventivo, correctivo y predictivo",
        ],
        applications: [
          "Públicos",
          "Industriales",
          "Comerciales",
          "Residenciales",
          "Edificaciones",
          "Centros de Salud",
          "Centros de Estudios",
          "Minería",
        ]
      },
      {
        id: "sistema-de-energia-ininterrumpida",
        title: "Sistema de energía ininterrumpida (UPS)",
        slug: "sistema-de-energia-ininterrumpida",
        description: "Suministro, instalación y mantenimiento de sistema de energía ininterrumpida (UPS).",
        image: "https://i.ibb.co/QFL5kTxL/sistemaups.jpg",
        detailedDescription: "Un sistema de energía ininterrumpida (UPS) es un dispositivo que proporciona energía eléctrica continua a equipos críticos durante interrupciones de la red eléctrica. Su función es proteger los equipos contra cortes de energía y garantizar el funcionamiento continuo de la instalación eléctrica. \n\n Industria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de Sistemas de Energía Ininterrumpida desde instalaciones hasta el mantenimiento.",
        benefits: [
          "Suministro de sistema de energía ininterrumpida",
          "Instalación de sistema de energía ininterrumpida",
          "Mantenimiento de sistema de energía ininterrumpida",
          "Mantenimiento de banco de baterías",
          "Prueba de sistema de energía ininterrumpida",
          "Optimización de los equipos e instalaciones",
          "Mantenimiento preventivo, correctivo y predictivo",
        ],
        applications: [
          "Públicos",
          "Industriales",
          "Comerciales",
          "Residenciales",
          "Edificaciones",
          "Centros de Salud",
          "Centros de Estudios",
          "Minería",
        ]
      },
      {
        id: "canalizacion-electrica",
        title: "Canalización Eléctrica",
        slug: "canalizacion-electrica",
        description: "Suministro, instalación y mantenimiento de canalización eléctrica.",
        image: "https://i.ibb.co/2082DCFz/canalizacionelectrica.jpg",
        detailedDescription: "Las canalizaciones eléctricas son sistemas de tuberías, bandejas y otros ductos utilizados para proteger y guiar cables eléctricos de manera segura y eficiente. Su función es proteger los cables eléctricos contra daños mecánicos, químicos y eléctricos. \n\n Industria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de canalizaciones eléctricas desde instalaciones hasta el mantenimiento.",
        benefits: [
          "Instalaciones de canalizaciones eléctricas",
          "Instalación de bandeja portacable",
          "Dimensionamiento de tuberías eléctricas",
          "Instalación de tuberías RMC",
          "EMT (Electrodos Metálicos Tubulares)",
          "IMC (Instalaciones Metálicas Combinadas)",
          "Canaletas de PVC",
          "Optimización de los equipos e instalaciones",
          "Mantenimiento preventivo, correctivo y predictivo",
        ],
        applications: [
          "Públicos",
          "Industriales",
          "Comerciales",
          "Residenciales",
          "Edificaciones",
          "Centros de Salud",
          "Centros de Estudios",
          "Minería",
        ]
      },
      {
        id: "iluminacion-industrial",
        title: "Iluminación Industrial",
        slug: "iluminacion-industrial",
        description: "Suministro, instalación y mantenimiento de sistemas de iluminación.",
        image: "https://images.unsplash.com/photo-1605802608596-cbf5ee9a5783?q=80&w=1160&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        detailedDescription: "Los sistemas de iluminación son el conjunto de sistemas y equipos diseñados para proporcionar iluminación adecuada en ambientes de trabajo. Su función es mejorar la visibilidad y la seguridad en el lugar de trabajo.\n\nNuestros proyectos de iluminación industrial se adaptan a las necesidades específicas de cada cliente, empleando tecnología moderna y cumpliendo con las normativas vigentes para garantizar eficiencia y seguridad en cada instalación. \n\n Industria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios desde instalaciones hasta el mantenimiento de sistemas de iluminación.",
        benefits: [
          "Diseño de luminarias",
          "Instalación de luminarias",
          "Mantenimiento de luminarias",
          "Cambio de luminarias",
          "Instalación de luced led",
          "Instalación de lamparas de emergencia",
          "Instalación de luminarias con sensor de movimiento",
          "Optimización de los equipos e instalaciones",
        ],
        applications: [
          "Públicos",
          "Industriales",
          "Comerciales",
          "Residenciales",
          "Edificaciones",
          "Centros de Salud",
          "Centros de Estudios",
          "Minería",
        ]
      },
      {
        id: "tomacorrientes",
        title: "Tomacorrientes",
        slug: "tomacorrientes",
        description: "Suministro, instalación y mantenimiento de tomacorrientes.",
        image: "https://i.ibb.co/PZ8tvvR9/tomacorrientes.jpg",
        detailedDescription: "Los tomacorrientes son dispositivos que permiten conectar y desconectar aparatos eléctricos a la red eléctrica. Su función es proporcionar energía eléctrica a los aparatos eléctricos. \n\nNuestros proyectos de tomacorrientes se adaptan a las necesidades específicas de cada cliente, empleando tecnología moderna y cumpliendo con las normativas vigentes para garantizar eficiencia y seguridad en cada instalación. \n\n Industria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios desde instalaciones hasta el mantenimiento de tomacorrientes.",
        benefits: [
          "Instalación de tomacorrientes para exteriores",
          "Tomacorrientes para hospitales, hoteles, centros de estudios, etc.",
          "Tomacorrientes a prueba de agua",
          "Tomacorrientes con tapa",
          "Optimización de los equipos e instalaciones",
          "Mantenimiento preventivo, correctivo y predictivo",
        ],
        applications: [
          "Públicos",
          "Industriales",
          "Comerciales",
          "Residenciales",
          "Edificaciones",
          "Centros de Salud",
          "Centros de Estudios",
          "Minería",
        ]
      },
      {
        id: "postes-de-alumbrado",
        title: "Postes de Alumbrado",
        slug: "postes-de-alumbrado",
        description: "Suministro, instalación y mantenimiento de postes de alumbrado.",
        image: "https://images.unsplash.com/photo-1597502310092-31cdaa35b46d?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        detailedDescription: "Los postes de alumbrado son estructuras verticales diseñadas para soportar luminarias o luces que proporcionan iluminación en exteriores. Se utilizan para iluminar áreas públicas, comerciales, industriales y residenciles, asegurando visibilidad y seguridad en diferentes entornos. \n\nNuestros proyectos de postes de alumbrado se adaptan a las necesidades específicas de cada cliente, empleando tecnología moderna y cumpliendo con las normativas vigentes para garantizar eficiencia y seguridad en cada instalación. \n\n Industria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios para posts de alumbrado.",
        benefits: [
          "Instalación de postes de luz",
          "Mantenimiento de postes de luz",
          "Cambio de postes de luz",
          "Postes de luz con luminaria LED",
          "Poste de luz para luminaria solar",
          "Postes de alumbrado público",
          "Optimización de los equipos e instalaciones",
          "Mantenimiento preventivo, correctivo y predictivo",
        ],
        applications: [
          "Públicos",
          "Industriales",
          "Comerciales",
          "Residenciales",
          "Edificaciones",
          "Centros de Salud",
          "Centros de Estudios",
          "Minería",
        ]
      }
    ]
  },
  {
    id: "data-comunicaciones",
    title: "Data y Comunicaciones",
    slug: "data-comunicaciones",
    description: "Soluciones de data y comunicaciones para la industria.",
    subServices: [
      {
        id: "transformadores-aislamiento",
        title: "Transformadores de Aislamiento",
        slug: "transformadores-aislamiento",
        description: "Suministro, instalación y mantenimiento de transformadores de aislamiento.",
        image: "https://i.ibb.co/XZ7SXNHf/transformadores.jpg",
        detailedDescription: "Los transformadores de aislamiento son dispositivos que proporcionan aislamiento galvánico entre la red eléctrica y los equipos sensibles, protegiendo contra interferencias electromagnéticas y transitorios de tensión. Su función principal es proteger equipos críticos de perturbaciones eléctricas y mejorar la calidad de la energía. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de transformadores de aislamiento para proteger tus equipos críticos y garantizar una energía limpia y estable.",
        benefits: [
          "Suministro de transformadores de aislamiento",
          "Instalación de transformadores de aislamiento",
          "Mantenimiento de transformadores de aislamiento",
          "Dimensionamiento según carga",
          "Protección contra interferencias electromagnéticas",
          "Certificación de operatividad",
          "Optimización de los equipos e instalaciones",
          "Mantenimiento preventivo, correctivo y predictivo",
        ],
        applications: [
          "Centros de datos",
          "Salas de servidores",
          "Equipos médicos",
          "Laboratorios",
          "Centros de control",
          "Equipos de telecomunicaciones",
          "Sistemas industriales sensibles",
        ]
      },
      {
        id: "estabilizadores-tension",
        title: "Estabilizadores de Tensión",
        slug: "estabilizadores-tension",
        description: "Suministro, instalación y mantenimiento de estabilizadores de tensión.",
        image: "https://i.ibb.co/mrw7DvW9/estabilizadores.jpg",
        detailedDescription: "Los estabilizadores de tensión son equipos que regulan y mantienen constante el voltaje eléctrico suministrado a los equipos, protegiéndolos contra fluctuaciones de tensión. Su función es garantizar un suministro eléctrico estable y proteger equipos sensibles contra sobretensiones y subtensiones. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de estabilizadores de tensión para garantizar un suministro eléctrico estable y proteger tus equipos.",
        benefits: [
          "Suministro de estabilizadores de tensión",
          "Instalación de estabilizadores de tensión",
          "Mantenimiento de estabilizadores de tensión",
          "Dimensionamiento según necesidad",
          "Protección contra fluctuaciones de tensión",
          "Monitoreo de calidad de energía",
          "Optimización de los equipos e instalaciones",
          "Mantenimiento preventivo, correctivo y predictivo",
        ],
        applications: [
          "Centros de datos",
          "Equipos de cómputo",
          "Equipos médicos",
          "Laboratorios",
          "Telecomunicaciones",
          "Comercios",
          "Oficinas",
        ]
      },
      {
        id: "gabinetes-racks-servidores",
        title: "Gabinetes y Racks de Servidores",
        slug: "gabinetes-racks-servidores",
        description: "Suministro, instalación y configuración de gabinetes y racks de servidores.",
        image: "https://i.ibb.co/4nDyFjD1/servidores.jpg",
        detailedDescription: "Los gabinetes y racks de servidores son estructuras metálicas diseñadas para alojar y organizar equipos de TI, servidores, switches, routers y otros dispositivos de red de manera segura y eficiente. Su función es proporcionar una infraestructura ordenada, segura y con ventilación adecuada para equipos críticos de TI. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de gabinetes y racks de servidores para una correcta organización y protección de tu infraestructura de TI.",
        benefits: [
          "Suministro de gabinetes y racks",
          "Instalación de gabinetes y racks",
          "Organización de cableado estructurado",
          "Sistema de ventilación y refrigeración",
          "Gestión de cables (cable management)",
          "PDU (Unidades de Distribución de Energía)",
          "Sistema de seguridad y acceso",
          "Optimización del espacio",
        ],
        applications: [
          "Centros de datos",
          "Salas de servidores",
          "Salas de telecomunicaciones",
          "Oficinas corporativas",
          "Centros de control",
          "Instituciones educativas",
          "Hospitales",
        ]
      },
      {
        id: "aires-precision",
        title: "Aires de Precisión",
        slug: "aires-precision",
        description: "Suministro, instalación y mantenimiento de aires acondicionados de precisión.",
        image: "https://i.ibb.co/zh5fzfwG/airesprecision.jpg",
        detailedDescription: "Los aires de precisión son sistemas de climatización especializados diseñados para mantener condiciones ambientales estables de temperatura y humedad en ambientes críticos. Su función es garantizar el funcionamiento óptimo de equipos sensibles al calor y humedad, evitando sobrecalentamientos y fallas. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de aires de precisión para mantener condiciones ambientales óptimas en tus instalaciones críticas.",
        benefits: [
          "Suministro de aires de precisión",
          "Instalación de aires de precisión",
          "Mantenimiento de aires de precisión",
          "Control preciso de temperatura y humedad",
          "Monitoreo continuo de condiciones ambientales",
          "Sistema de respaldo redundante",
          "Eficiencia energética",
          "Mantenimiento preventivo, correctivo y predictivo",
        ],
        applications: [
          "Centros de datos",
          "Salas de servidores",
          "Salas de telecomunicaciones",
          "Laboratorios",
          "Salas blancas",
          "Centros de control",
          "Equipos médicos especializados",
        ]
      },
      {
        id: "cableado-estructurado",
        title: "Cableado Estructurado",
        slug: "cableado-estructurado",
        description: "Diseño, instalación y certificación de sistemas de cableado estructurado.",
        image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        detailedDescription: "El cableado estructurado es un sistema de cables, conectores y dispositivos que proporciona una infraestructura de telecomunicaciones completa y estandarizada para transmisión de datos, voz y video. Su función es proporcionar una red confiable, escalable y de alto rendimiento para todas las necesidades de comunicación. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de cableado estructurado desde el diseño hasta la certificación de tu red de datos.",
        benefits: [
          "Diseño de red de cableado estructurado",
          "Instalación de cableado categoría 6, 6A y 7",
          "Instalación de fibra óptica",
          "Certificación de red de datos",
          "Etiquetado y documentación completa",
          "Instalación de patch panels",
          "Instalación de face plates",
          "Testing y troubleshooting",
          "Garantía de por vida en instalación",
        ],
        applications: [
          "Oficinas corporativas",
          "Centros de datos",
          "Edificios comerciales",
          "Instituciones educativas",
          "Hospitales",
          "Hoteles",
          "Centros comerciales",
        ]
      },
      {
        id: "tomadatas",
        title: "Tomadatas",
        slug: "tomadatas",
        description: "Suministro, instalación y certificación de tomadatas (puntos de red).",
        image: "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        detailedDescription: "Los tomadatas son puntos de conexión de red que permiten conectar dispositivos a la infraestructura de red de datos. Son el punto de acceso final del cableado estructurado donde se conectan computadoras, teléfonos IP, puntos de acceso WiFi y otros dispositivos de red. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de tomadatas para una correcta conectividad de tus equipos de red.",
        benefits: [
          "Instalación de tomadatas RJ45",
          "Tomadatas categoría 6, 6A y 7",
          "Instalación de face plates",
          "Certificación de puntos de red",
          "Etiquetado y documentación",
          "Tomadatas para fibra óptica",
          "Tomadatas para voz y datos",
          "Testing de conectividad",
        ],
        applications: [
          "Oficinas",
          "Puestos de trabajo",
          "Salas de reuniones",
          "Áreas comunes",
          "Laboratorios",
          "Aulas",
          "Consultorios",
        ]
      }
    ]
  },
  {
    id: "seguridad-electronica",
    title: "Seguridad Electrónica",
    slug: "seguridad-electronica",
    description: "Soluciones de seguridad electrónica para la industria.",
    subServices: [
      {
        id: "camaras-videovigilancia",
        title: "Cámaras de Videovigilancia",
        slug: "camaras-videovigilancia",
        description: "Suministro, instalación y mantenimiento de sistemas de videovigilancia.",
        image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        detailedDescription: "Los sistemas de videovigilancia son conjuntos de cámaras y equipos de grabación que permiten monitorear y grabar actividades en tiempo real para garantizar la seguridad de personas, bienes e instalaciones. Su función es prevenir, detectar y registrar incidentes de seguridad, proporcionando evidencia visual y disuadiendo actividades delictivas. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de videovigilancia desde el diseño hasta el mantenimiento de tu sistema de seguridad.",
        benefits: [
          "Diseño de sistema de videovigilancia",
          "Instalación de cámaras IP y analógicas",
          "Cámaras de alta resolución (Full HD, 4K)",
          "Cámaras con visión nocturna",
          "Grabación y almacenamiento (DVR/NVR)",
          "Acceso remoto desde dispositivos móviles",
          "Análisis de video inteligente",
          "Integración con sistemas de alarma",
          "Mantenimiento preventivo y correctivo",
        ],
        applications: [
          "Edificios corporativos",
          "Plantas industriales",
          "Comercios y tiendas",
          "Almacenes y depósitos",
          "Estacionamientos",
          "Perímetros de seguridad",
          "Áreas residenciales",
          "Instituciones educativas",
        ]
      },
      {
        id: "intercomunicadores",
        title: "Intercomunicadores",
        slug: "intercomunicadores",
        description: "Suministro, instalación y configuración de sistemas de intercomunicación.",
        image: "https://i.ibb.co/Lh1dzJzv/intercomunicadores.png",
        detailedDescription: "Los intercomunicadores son sistemas de comunicación bidireccional que permiten la comunicación de audio y/o video entre diferentes puntos de acceso y estaciones internas. Su función es facilitar la comunicación segura entre visitantes y residentes o personal autorizado, mejorando el control de accesos. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de intercomunicadores para una comunicación segura y eficiente en tus instalaciones.",
        benefits: [
          "Instalación de intercomunicadores de audio",
          "Intercomunicadores con video (videoporteros)",
          "Sistemas IP y analógicos",
          "Integración con control de accesos",
          "Apertura remota de puertas",
          "Múltiples estaciones internas",
          "Grabación de llamadas",
          "App móvil para atención remota",
          "Mantenimiento preventivo y correctivo",
        ],
        applications: [
          "Edificios residenciales",
          "Condominios",
          "Oficinas corporativas",
          "Plantas industriales",
          "Hospitales",
          "Colegios",
          "Centros comerciales",
          "Hoteles",
        ]
      },
      {
        id: "alarmas-intrusion",
        title: "Alarmas de Intrusión",
        slug: "alarmas-intrusion",
        description: "Suministro, instalación y monitoreo de sistemas de alarmas de intrusión.",
        image: "https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        detailedDescription: "Los sistemas de alarmas de intrusión son conjuntos de sensores y dispositivos que detectan accesos no autorizados o intentos de intrusión en una propiedad, activando alertas sonoras y/o visuales. Su función es proteger instalaciones contra intrusiones, robos y accesos no autorizados mediante detección temprana y notificación inmediata. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de alarmas de intrusión para proteger tus instalaciones las 24 horas del día.",
        benefits: [
          "Diseño de sistema de alarmas",
          "Instalación de sensores de movimiento",
          "Sensores magnéticos para puertas y ventanas",
          "Detectores de rotura de vidrio",
          "Sirenas de alta potencia",
          "Panel de control con teclado",
          "Notificaciones por app móvil",
          "Monitoreo remoto 24/7",
          "Integración con videovigilancia",
          "Mantenimiento preventivo y correctivo",
        ],
        applications: [
          "Viviendas residenciales",
          "Oficinas",
          "Comercios",
          "Almacenes",
          "Plantas industriales",
          "Bodegas",
          "Consultorios",
          "Instituciones educativas",
        ]
      },
      {
        id: "cerco-electrico",
        title: "Cerco Eléctrico",
        slug: "cerco-electrico",
        description: "Suministro, instalación y mantenimiento de sistemas de cercos eléctricos.",
        image: "https://i.ibb.co/5g31Qt4b/cercoelectrico.jpg",
        detailedDescription: "Los cercos eléctricos son sistemas de seguridad perimetral compuestos por alambres electrificados con pulsos de alta tensión y baja corriente que generan una barrera de protección disuasiva. Su función es proteger el perímetro de una propiedad mediante una barrera electrificada que disuade y detecta intentos de intrusión. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de cercos eléctricos para una protección perimetral efectiva de tus instalaciones.",
        benefits: [
          "Diseño e instalación de cerco eléctrico",
          "Energizadores de alta y baja tensión",
          "Pulsos de seguridad (no letales)",
          "Alarma de intento de intrusión",
          "Alarma de corte de cables",
          "Respaldo con batería",
          "Certificación de instalación",
          "Señalización de seguridad",
          "Integración con sistema de alarmas",
          "Mantenimiento preventivo y correctivo",
        ],
        applications: [
          "Perímetros residenciales",
          "Plantas industriales",
          "Almacenes",
          "Centros comerciales",
          "Edificios corporativos",
          "Instituciones educativas",
          "Hospitales",
          "Instalaciones gubernamentales",
        ]
      }
    ]
  },
  {
    id: "electromecanica",
    title: "Electromecánica",
    slug: "electromecanica",
    description: "Soluciones de electromecánica para la industria.",
    subServices: [
      {
        id: "grupo-electrogeno",
        title: "Grupo Electrógeno",
        slug: "grupo-electrogeno",
        description: "Suministro, instalación y mantenimiento de grupos electrógenos.",
        image: "https://i.ibb.co/kgPkdQj3/grupoelectrogeno.jpg",
        detailedDescription: "Los grupos electrógenos son equipos que generan energía eléctrica de forma autónoma mediante un motor de combustión interna acoplado a un generador eléctrico. Su función es proporcionar energía eléctrica de respaldo en caso de cortes de suministro o como fuente principal en ubicaciones sin acceso a la red eléctrica. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de grupos electrógenos para garantizar continuidad eléctrica en tus instalaciones.",
        benefits: [
          "Suministro de grupos electrógenos",
          "Instalación de grupos electrógenos",
          "Mantenimiento preventivo y correctivo",
          "Grupos electrógenos diésel y a gas",
          "Tableros de transferencia automática (ATS)",
          "Dimensionamiento según carga",
          "Pruebas de carga",
          "Sincronización de generadores",
          "Sistemas de monitoreo remoto",
          "Repuestos y servicio técnico",
        ],
        applications: [
          "Hospitales y clínicas",
          "Centros de datos",
          "Plantas industriales",
          "Centros comerciales",
          "Hoteles",
          "Edificios corporativos",
          "Minería",
          "Telecomunicaciones",
        ]
      },
      {
        id: "motores-electricos",
        title: "Motores Eléctricos",
        slug: "motores-electricos",
        description: "Suministro, instalación y mantenimiento de motores eléctricos industriales.",
        image: "https://i.ibb.co/x86bKgxc/motoreselectricos.jpg",
        detailedDescription: "Los motores eléctricos son máquinas que convierten energía eléctrica en energía mecánica mediante campos electromagnéticos. Son fundamentales en procesos industriales para accionar bombas, ventiladores, compresores, transportadores y todo tipo de maquinaria. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de motores eléctricos para optimizar tus procesos industriales.",
        benefits: [
          "Suministro de motores eléctricos",
          "Instalación de motores eléctricos",
          "Mantenimiento preventivo y correctivo",
          "Motores trifásicos y monofásicos",
          "Rebobinado de motores",
          "Balanceo dinámico",
          "Cambio de rodamientos",
          "Pruebas eléctricas y mecánicas",
          "Análisis de vibración",
          "Optimización de eficiencia energética",
        ],
        applications: [
          "Plantas industriales",
          "Sistemas de bombeo",
          "Sistemas de ventilación",
          "Máquinas herramientas",
          "Transportadores",
          "Compresores",
          "Equipos de refrigeración",
          "Líneas de producción",
        ]
      },
      {
        id: "bombas-agua",
        title: "Bombas de Agua",
        slug: "bombas-agua",
        description: "Suministro, instalación y mantenimiento de sistemas de bombeo de agua.",
        image: "https://i.ibb.co/3yfS4d8m/bomasdeagua.jpg",
        detailedDescription: "Las bombas de agua son equipos electromecánicos diseñados para mover fluidos de un lugar a otro mediante la creación de diferencias de presión. Son esenciales para sistemas de abastecimiento de agua, riego, drenaje, procesos industriales y sistemas contra incendios. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de bombas de agua para cubrir todas tus necesidades de bombeo.",
        benefits: [
          "Suministro de bombas de agua",
          "Instalación de sistemas de bombeo",
          "Mantenimiento preventivo y correctivo",
          "Bombas centrífugas y periféricas",
          "Bombas sumergibles",
          "Electrobombas de alta presión",
          "Dimensionamiento hidráulico",
          "Tableros de control automático",
          "Sistemas contra incendios",
          "Repuestos y servicio técnico",
        ],
        applications: [
          "Abastecimiento de agua potable",
          "Sistemas de riego",
          "Drenaje y achique",
          "Procesos industriales",
          "Sistemas contra incendios",
          "Torres de enfriamiento",
          "Piscinas",
          "Edificios residenciales y comerciales",
        ]
      },
      {
        id: "ventilacion-industrial",
        title: "Ventilación Industrial",
        slug: "ventilacion-industrial",
        description: "Diseño, instalación y mantenimiento de sistemas de ventilación industrial.",
        image: "https://i.ibb.co/gbXG8BjL/ventilacionindustrial.jpg",
        detailedDescription: "Los sistemas de ventilación industrial son conjuntos de equipos diseñados para renovar el aire, controlar la temperatura, humedad y eliminar contaminantes en ambientes industriales. Su función es garantizar condiciones ambientales adecuadas para procesos productivos y la salud de los trabajadores. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de ventilación industrial para mejorar la calidad del aire en tus instalaciones.",
        benefits: [
          "Diseño de sistemas de ventilación",
          "Instalación de extractores industriales",
          "Ventiladores axiales y centrífugos",
          "Sistemas de inyección y extracción",
          "Ductos y campanas de extracción",
          "Filtros de aire industrial",
          "Sistemas de control automático",
          "Cálculo de caudales y velocidades",
          "Mantenimiento preventivo y correctivo",
          "Optimización energética",
        ],
        applications: [
          "Plantas industriales",
          "Talleres mecánicos",
          "Naves industriales",
          "Cocinas industriales",
          "Almacenes",
          "Fundiciones",
          "Laboratorios",
          "Centros de manufactura",
        ]
      }
    ]
  },
  {
    id: "automatizacion-instrumentacion",
    title: "Automatización e Instrumentación",
    slug: "automatizacion-instrumentacion",
    description: "Soluciones de automatización e instrumentación para la industria.",
    subServices: [
      {
        id: "domotica",
        title: "Domótica",
        slug: "domotica",
        description: "Diseño e instalación de sistemas domóticos para automatización de viviendas y edificios.",
        image: "https://i.ibb.co/tn1Gvtp/domotica.jpg",
        detailedDescription: "La domótica es el conjunto de tecnologías aplicadas al control y automatización inteligente de viviendas y edificios, permitiendo gestionar de manera eficiente la iluminación, climatización, seguridad, comunicaciones y otros sistemas. Su función es mejorar el confort, seguridad, eficiencia energética y comunicaciones en espacios habitables mediante la automatización y control inteligente. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de domótica para convertir tu hogar o edificio en un espacio inteligente y eficiente.",
        benefits: [
          "Diseño de sistemas domóticos",
          "Automatización de iluminación",
          "Control de climatización",
          "Cortinas y persianas motorizadas",
          "Control por app móvil",
          "Integración con asistentes de voz",
          "Escenas y programaciones",
          "Ahorro energético",
          "Control de accesos",
          "Seguridad integrada",
        ],
        applications: [
          "Viviendas inteligentes",
          "Departamentos",
          "Oficinas",
          "Hoteles",
          "Edificios corporativos",
          "Centros comerciales",
          "Consultorios",
          "Showrooms",
        ]
      },
      {
        id: "controladores-sensores-medidores",
        title: "Controladores, Sensores y Medidores",
        slug: "controladores-sensores-medidores",
        description: "Suministro, instalación y programación de controladores, sensores y medidores industriales.",
        image: "https://i.ibb.co/cKPnhC4x/Gemini-Generated-Image-m2yvyym2yvyym2yv.png",
        detailedDescription: "Los controladores, sensores y medidores son dispositivos fundamentales en sistemas de automatización industrial que permiten monitorear, medir y controlar variables de proceso como temperatura, presión, nivel, flujo, humedad y otras magnitudes físicas. Su función es proporcionar información en tiempo real de los procesos industriales y ejecutar acciones de control automático para optimizar la operación. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de instrumentación para el monitoreo y control preciso de tus procesos industriales.",
        benefits: [
          "Suministro de controladores PLC",
          "Sensores de temperatura y humedad",
          "Sensores de presión y nivel",
          "Medidores de flujo",
          "Transmisores analógicos",
          "Analizadores de calidad",
          "Programación de controladores",
          "Calibración de instrumentos",
          "Integración con sistemas SCADA",
          "Mantenimiento preventivo",
        ],
        applications: [
          "Plantas industriales",
          "Procesos químicos",
          "Tratamiento de agua",
          "Sistemas HVAC",
          "Líneas de producción",
          "Sistemas de refrigeración",
          "Industria alimentaria",
          "Minería y metalurgia",
        ]
      },
      {
        id: "tableros-control",
        title: "Tableros de Control",
        slug: "tableros-control",
        description: "Diseño, fabricación e instalación de tableros de control y automatización.",
        image: "https://i.ibb.co/bjR2LSRF/tablerosdecontrol.webp",
        detailedDescription: "Los tableros de control son gabinetes que contienen equipos de control, protección y automatización para gestionar procesos industriales de manera eficiente y segura. Integran PLCs, HMIs, variadores de frecuencia, contactores y otros dispositivos de control. Su función es centralizar el comando y monitoreo de procesos automatizados, proporcionando una interfaz de operación segura y eficiente. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de tableros de control personalizados para tus necesidades de automatización.",
        benefits: [
          "Diseño personalizado de tableros",
          "Integración de PLC y HMI",
          "Tableros con variadores de frecuencia",
          "Sistemas de arranque de motores",
          "Cableado estructurado interno",
          "Sistemas de protección",
          "Documentación técnica completa",
          "Pruebas FAT (Factory Acceptance Test)",
          "Puesta en marcha",
          "Capacitación de operadores",
        ],
        applications: [
          "Automatización de procesos",
          "Sistemas de bombeo",
          "Líneas de producción",
          "Máquinas especiales",
          "Sistemas de tratamiento",
          "Equipos de refrigeración",
          "Plantas de procesamiento",
          "Sistemas de transporte",
        ]
      }
    ]
  },
  {
    id: "construccion-arquitectura",
    title: "Construcción y Arquitectura",
    slug: "construccion-arquitectura",
    description: "Soluciones de construcción y arquitectura para la industria.",
    subServices: [
      {
        id: "edificaciones-obras-civiles",
        title: "Edificaciones y Obras Civiles",
        slug: "edificaciones-obras-civiles",
        description: "Construcción de edificaciones y desarrollo de proyectos de obra civil.",
        image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1476&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        detailedDescription: "Las edificaciones y obras civiles son proyectos de construcción que abarcan desde estructuras residenciales y comerciales hasta infraestructura pública como carreteras, puentes y obras de saneamiento. Su función es crear espacios funcionales y seguros que cumplan con las normativas vigentes y satisfagan las necesidades de sus usuarios. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de construcción desde el diseño hasta la entrega de proyectos de edificación y obra civil.",
        benefits: [
          "Diseño y planificación de proyectos",
          "Construcción de edificaciones",
          "Obra civil e infraestructura",
          "Gestión integral de proyectos",
          "Estudios de suelos y estructuras",
          "Supervisión técnica especializada",
          "Control de calidad en obra",
          "Cumplimiento de normativas",
          "Licencias y permisos",
          "Garantía estructural",
        ],
        applications: [
          "Edificios residenciales",
          "Edificios comerciales",
          "Naves industriales",
          "Carreteras y vías",
          "Puentes y viaductos",
          "Obras de saneamiento",
          "Pavimentación",
          "Infraestructura pública",
        ]
      },
      {
        id: "remodelaciones-drywall",
        title: "Remodelaciones y Drywall",
        slug: "remodelaciones-drywall",
        description: "Servicios de remodelación de espacios y sistemas constructivos en drywall.",
        image: "https://i.ibb.co/0VcBMJZ7/remodelacionesdrywall.jpg",
        detailedDescription: "Las remodelaciones y drywall son servicios de renovación y construcción de espacios interiores utilizando sistemas livianos de construcción en seco. El drywall (también conocido como placa de yeso o panel de yeso) permite crear divisiones, cielos rasos y estructuras internas de manera rápida y eficiente. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de remodelación y construcción en drywall para transformar tus espacios con acabados modernos y funcionales.",
        benefits: [
          "Remodelación integral de espacios",
          "Instalación de drywall",
          "Cielos rasos y cielos falsos",
          "Divisiones y tabiquería",
          "Aislamiento térmico y acústico",
          "Diseño de interiores",
          "Optimización de espacios",
          "Instalación rápida y limpia",
          "Acabados de primera calidad",
          "Mínima interrupción de operaciones",
        ],
        applications: [
          "Oficinas corporativas",
          "Locales comerciales",
          "Consultorios médicos",
          "Viviendas",
          "Hoteles",
          "Restaurantes",
          "Centros educativos",
          "Salas de reuniones",
        ]
      },
      {
        id: "revestimiento-pintura",
        title: "Revestimiento y Pintura",
        slug: "revestimiento-pintura",
        description: "Servicios de revestimiento de superficies y trabajos de pintura profesional.",
        image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        detailedDescription: "Los servicios de revestimiento y pintura comprenden la aplicación de materiales de acabado en superficies interiores y exteriores para proteger, decorar y embellecer espacios. Incluyen revestimientos cerámicos, porcelanatos, enchapes y diversos tipos de pintura profesional. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de revestimiento y pintura para darle un acabado impecable a tus proyectos.",
        benefits: [
          "Revestimiento cerámico y porcelanato",
          "Enchapes de piedra natural",
          "Pintura interior y exterior",
          "Pintura decorativa",
          "Pintura epóxica industrial",
          "Texturizados y acabados especiales",
          "Preparación de superficies",
          "Impermeabilización",
          "Asesoría en selección de colores",
          "Garantía de aplicación",
        ],
        applications: [
          "Viviendas residenciales",
          "Edificios comerciales",
          "Oficinas",
          "Fachadas",
          "Baños y cocinas",
          "Pisos y paredes",
          "Áreas industriales",
          "Áreas comunes",
        ]
      },
      {
        id: "carpinteria-vidrieria",
        title: "Carpintería y Vidriería",
        slug: "carpinteria-vidrieria",
        description: "Fabricación e instalación de trabajos de carpintería y vidriería.",
        image: "https://i.ibb.co/hRCV0qHg/vidrieriacarp.jpg",
        detailedDescription: "Los servicios de carpintería y vidriería incluyen el diseño, fabricación e instalación de elementos de madera, aluminio y vidrio para espacios arquitectónicos. Comprenden puertas, ventanas, muebles a medida, mamparas, barandas y estructuras de vidrio templado. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con diversos servicios de carpintería y vidriería para complementar tus proyectos con acabados elegantes y funcionales.",
        benefits: [
          "Carpintería en madera y melamina",
          "Muebles a medida",
          "Puertas y ventanas",
          "Closets y reposteros",
          "Mamparas de vidrio templado",
          "Ventanas de aluminio y vidrio",
          "Barandas y pasamanos",
          "Espejos decorativos",
          "Vitrinas y exhibidores",
          "Instalación profesional",
        ],
        applications: [
          "Viviendas",
          "Oficinas",
          "Locales comerciales",
          "Restaurantes",
          "Hoteles",
          "Baños",
          "Cocinas",
          "Showrooms",
        ]
      }
    ]
  },
  {
    id: "ingenieria-consultoria",
    title: "Ingeniería y Consultoría",
    slug: "ingenieria-consultoria",
    description: "Servicios de ingeniería y consultoría para tus proyectos.",
    subServices: [
      {
        id: "diseno-planos-arquitectonicos",
        title: "Diseño de Planos Arquitectónicos",
        slug: "diseno-planos-arquitectonicos",
        description: "Diseño y elaboración de planos arquitectónicos y de ingeniería.",
        image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1631&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        detailedDescription: "El diseño de planos arquitectónicos es el proceso de creación de documentos técnicos que representan gráficamente la distribución, dimensiones, especificaciones y detalles constructivos de un proyecto. Incluye planos arquitectónicos, estructurales, eléctricos, sanitarios y de especialidades. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con servicios de diseño de planos profesionales para materializar tus proyectos con precisión y cumpliendo todas las normativas vigentes.",
        benefits: [
          "Diseño arquitectónico",
          "Planos de arquitectura",
          "Planos estructurales",
          "Planos de instalaciones eléctricas",
          "Planos de instalaciones sanitarias",
          "Planos de instalaciones mecánicas",
          "Modelado 3D y renderizado",
          "Documentación técnica completa",
          "Cumplimiento de normativas",
          "Asesoría técnica especializada",
        ],
        applications: [
          "Proyectos residenciales",
          "Proyectos comerciales",
          "Proyectos industriales",
          "Remodelaciones",
          "Ampliaciones",
          "Licencias de construcción",
          "Regularización de edificaciones",
          "Proyectos de infraestructura",
        ]
      },
      {
        id: "gestion-proyectos",
        title: "Gestión de Proyectos",
        slug: "gestion-proyectos",
        description: "Gestión integral y dirección de proyectos de construcción e ingeniería.",
        image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        detailedDescription: "La gestión de proyectos es la aplicación de conocimientos, habilidades, herramientas y técnicas para ejecutar proyectos de manera eficiente, cumpliendo con los objetivos de tiempo, costo y calidad establecidos. Comprende la planificación, coordinación, control y cierre de proyectos. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con servicios de gestión de proyectos para garantizar el éxito de tus inversiones desde la concepción hasta la entrega final.",
        benefits: [
          "Planificación de proyectos",
          "Elaboración de cronogramas",
          "Control de presupuestos",
          "Coordinación multidisciplinaria",
          "Gestión de recursos",
          "Control de calidad",
          "Gestión de riesgos",
          "Gestión de proveedores",
          "Informes de avance",
          "Entrega en tiempo y forma",
        ],
        applications: [
          "Proyectos de construcción",
          "Proyectos industriales",
          "Proyectos de infraestructura",
          "Proyectos eléctricos",
          "Proyectos de automatización",
          "Proyectos tecnológicos",
          "Remodelaciones",
          "Expansiones industriales",
        ]
      },
      {
        id: "supervision-asesoria-legal",
        title: "Supervisión y Asesoría Legal",
        slug: "supervision-asesoria-legal",
        description: "Supervisión de obras y asesoría legal para proyectos de construcción.",
        image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1471&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        detailedDescription: "La supervisión de obras es el servicio de control y verificación del cumplimiento de especificaciones técnicas, planos y normativas durante la ejecución de proyectos de construcción. La asesoría legal comprende el apoyo en aspectos normativos, contractuales y de permisos relacionados con proyectos de construcción e ingeniería. \n\nIndustria RLC está comprometido con ofrecerte soluciones de alta calidad. Contamos con servicios de supervisión técnica y asesoría legal para garantizar que tus proyectos cumplan con todas las normativas y se ejecuten correctamente.",
        benefits: [
          "Supervisión técnica de obra",
          "Control de calidad en campo",
          "Verificación de cumplimiento de planos",
          "Informes técnicos periódicos",
          "Asesoría en normativas de construcción",
          "Gestión de licencias y permisos",
          "Regularización de edificaciones",
          "Asesoría en contratos de construcción",
          "Resolución de conflictos técnicos",
          "Certificaciones de obra",
        ],
        applications: [
          "Obras de construcción",
          "Proyectos industriales",
          "Remodelaciones",
          "Proyectos eléctricos",
          "Licencias municipales",
          "Defensa civil",
          "Regularización de inmuebles",
          "Contratos de obra",
        ]
      }
    ]
  }
]